// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/add-maintenance': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/add-maintenance.post').default>>>>
    }
    '/api/admin/all-portal-vehicles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/all-portal-vehicles.get').default>>>>
    }
    '/api/admin/create-portal-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/create-portal-user.post').default>>>>
    }
    '/api/admin/delete-maintenance': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/delete-maintenance.delete').default>>>>
    }
    '/api/admin/delete-portal-document': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/delete-portal-document.delete').default>>>>
    }
    '/api/admin/delete-portal-user': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/delete-portal-user.delete').default>>>>
    }
    '/api/admin/portal-data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/portal-data.get').default>>>>
    }
    '/api/admin/trade-ins': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/trade-ins.get').default>>>>
    }
    '/api/admin/update-portal-vehicle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/update-portal-vehicle.post').default>>>>
    }
    '/api/admin/upload-portal-document': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload-portal-document.post').default>>>>
    }
    '/api/auth/portal-login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/portal-login.post').default>>>>
    }
    '/api/blog/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/[id].put').default>>>>
    }
    '/api/blog/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/[slug].get').default>>>>
    }
    '/api/blog': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/index.post').default>>>>
    }
    '/api/blog/maintenance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/maintenance.get').default>>>>
    }
    '/api/blog/related': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/related.get').default>>>>
    }
    '/api/debug-blog': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-blog.get').default>>>>
    }
    '/api/leads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads.post').default>>>>
    }
    '/api/portal/data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/portal/data.get').default>>>>
    }
    '/api/trade-ins': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trade-ins.post').default>>>>
    }
    '/api/veicoli': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/veicoli.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/veicoli.post').default>>>>
    }
    '/api/veicoli/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/veicoli/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/veicoli/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/veicoli/[id].put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/__sitemap__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.6.0_magic_362e2a1ffcd36e4f21a510d5b80247b4/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/__sitemap__/debug').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.6.0_magic_362e2a1ffcd36e4f21a510d5b80247b4/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.6.0_magic_362e2a1ffcd36e4f21a510d5b80247b4/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xml').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_631e74ece614e16f0549727fc9d9ed71/node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}